sever.port:
springdoc:
  swagger-ui:
    enable: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:mysql.//localhost:3306/
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
token:
  secret-key: ""
  refresh-secret-key: ""
  token-time: 300
  refresh-token-time: 300